package com.mega.mvc06;

public class Problem06Main2 {

	public static void main(String[] args) {
		Problem06 error = new Problem06();
		try {
			error.call(); 
		} catch (Exception e) {
			System.out.println("호출한 곳에서 다르게 알아서 처리함 ");
		}
		System.out.println("에러 발생후 실행이 될까요 ? ");
		System.out.println("에러 발생후 실행이 될까요 ? ");
		System.out.println("에러 발생후 실행이 될까요 ? ");
		System.out.println("에러 발생후 실행이 될까요 ? ");
		System.out.println("에러 발생후 실행이 될까요 ? ");
		System.out.println("에러 발생후 실행이 될까요 ? ");
		System.out.println("에러 발생후 실행이 될까요 ? ");
		System.out.println("에러 발생후 실행이 될까요 ? ");
	}

}
